### DISCUSSION TITLE
data generation for crop segmentation workflow failed

### DISCUSSION THREAD

**Discussion by mursaleen-bkk** [microsoft/farmvibes-ai#75] [Q&A] [answered]
I run the detagen_crop_segmentation to download the data of the same given area by farmvibes from 2020/1/1 to 2020/1/5. To download data for only five days. But the workflow failed as show in the given figure.
![image](https://user-images.githubusercontent.com/117431087/226538717-23b5a701-3a13-45b8-ad90-74f25d48bb97.png)

**Comment by rafaspadilha** [comment]
Hi, @mursaleen-bkk.

To help us understand the isse, whenever you have a failed workflow, please make sure to share the outputs of `wf_run.reason` and `wf_run.task_details`.

Considering what you described, SpaceEye requires a window of time of at least 3 months in order to remove the clouds.

If you are interested in the Sentinel-2 images, you can adapt the `notebooks/crop_segmentation/wf_viz_crop_seg.yaml` custom workflow to ignore the SpaceEye task and get the S-2 images as sinks. An example would be:

```
name: visualize_crop_segmentation
sources:
  user_input:
    - s2.user_input
    - cdl.user_input
sinks:
  s2_rasters: s2.raster ### NEW SINK FOR VISUALIZATION
  s2_masks: s2.mask ### NEW SINK FOR VISUALIZATION
  cdl: cdl.raster
parameters:
  pc_key:
tasks:
  s2: ### NEW TASK FOR VISUALIZATION
    workflow: data_ingestion/sentinel2/preprocess_s2_improved_masks
  cdl:
    workflow: data_ingestion/cdl/download_cdl
edges:
```

Please, let me know if that solves your issue
