### ISSUE TITLE
Error when importing SAM ONNX models to cluster

### ISSUE THREAD

**Issue by marias65** [microsoft/farmvibes-ai#161]
Currently trying to follow the segment anything notebook to run sentinel2_segmentation.ipynb but when trying to import SAM's ONNX models to the cluster with `! python ../../scripts/export_sam_models.py --models vit_b`, I run into an error that says "ImportError: /home/msbksan/micromamba/envs/segment_anything_cpu/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent"

**Comment by rafaspadilha** [comment]
Hi, @marias65. I couldn't reproduce your error on my machine but found a few similar issues [here](https://stackoverflow.com/questions/78328401/libtorch-cpu-so-undefined-symbol-ijit-isprofilingactive) and [here](https://github.com/intel/intel-extension-for-pytorch/issues/317) that the cause might be installing pytorch via conda and a possible solution would be pointing to the CPU wheel during installation. 


Quick question: are you able to import PyTorch in the `segment_anything_cpy` environment?
```bash
$ python -c "import torch; print(torch.__version__)"
```

I was able to set up a new environment with the latest version of PyTorch and run the script to export the model to ONNX files. Could I ask you to try on your end as well?

Please change the `env_cpy.yaml`, commenting the `pip` lines as below:
```yaml
name: new_segment_anything_cpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.8.*
  - geopandas~=0.11.1
  - ipython~=8.5.0
  - ipywidgets~=8.0.2
  - jupyter~=1.0.0
  - matplotlib~=3.6.0
  - numpy~=1.23.3
  # - pytorch=2.0.0=py3.8_cpu_0
  # - torchvision=0.15.0=py38_cpu
  # - torchaudio=2.0.0=py38_cpu
  - pip~=22.2.0
  - pandas~=1.5.0
  - rasterio~=1.3.2
  - shapely~=1.8.4
  - tqdm~=4.64.1
  - scikit-image~=0.20.0
  # - pip:
  #     - git+https://github.com/facebookresearch/segment-anything.git
  #     - ../../src/vibe_core
  #     - cartopy~=0.21.0
  #     - xarray~=2022.10.0
  #     - ipympl~=0.9.3
  #     - onnx~=1.14.0
  #     - onnxruntime~=1.15.0
```

Once the env is created, please activate it and install the pip packages:
```bash
$ micromamba activate new_segment_anything_cpu
$ pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
$ pip install git+https://github.com/facebookresearch/segment-anything.git 
$ pip install ../../src/vibe_core 
$ pip install cartopy~=0.21.0 xarray~=2022.10.0 ipympl~=0.9.3 onnx~=1.14.0 onnxruntime~=1.15.0
```

Please, make sure the path to `src/vibe_core` is correct on the `$ pip install ../../src/vibe_core` command.

**Comment by marias65** [comment]
Thank you for your response! I was not able to run `$ python -c "import torch; print(torch.__version__)"` as it gave me the same iJIT_NotifyEvent error while in the `segment_anything_cpu` environment.

 I was able to create the new_segment_anything_cpu environment and install all the pip packages you listed but when I attempted to run `$ python -c "import torch; print(torch.__version__)"` or `! python ../../scripts/export_sam_models.py --models vit_b` I still came across the same iJIT_NotifyEvent error.

![image](https://github.com/microsoft/farmvibes-ai/assets/114122115/4e69accc-8eeb-4e4f-a1b3-f175ca05209f)

**Comment by rafaspadilha** [comment]
Hi, @marias65. I was able to replicate your issue.

Installing the new version of pytorch with the appropriate wheel solved the problem for me:

`pip install torch~=2.1.0 --index-url https://download.pytorch.org/whl/cpu`

Please, could you let me know if this works for you?

**Comment by rafaspadilha** [comment]
Another possibility that worked for me was creating the environment with the following yaml:

```yaml
name: segment_anything_cpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.8.*
  - geopandas~=0.11.1
  - ipython~=8.5.0
  - ipywidgets~=8.0.2
  - jupyter~=1.0.0
  - matplotlib~=3.6.0
  - numpy~=1.23.3
  - pip~=22.2.0
  - pandas~=1.5.0
  - rasterio~=1.3.2
  - shapely~=1.8.4
  - tqdm~=4.64.1
  - scikit-image~=0.20.0
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch~=2.0.0
      - torchvision~=0.15.0
      - torchaudio~=2.0.0
      - git+https://github.com/facebookresearch/segment-anything.git
      - ../../src/vibe_core
      - cartopy~=0.21.0
      - xarray~=2022.10.0
      - ipympl~=0.9.3
      - onnx~=1.14.0
      - onnxruntime~=1.15.0
```

by running:

```$ micromamba env create -f notebooks/segment_anything/env_cpu.yaml```
