### ISSUE TITLE
SpaceEye & NDVI Timelapse workflow creates rasters and lapses for future dates

### ISSUE THREAD

**Issue by richstep** [microsoft/farmvibes-ai#87]
My time range is from March 13 to April 12 (today is April 13), yet I get output for April 15th and 20th, 2023.

`time_range = (datetime(2023, 3, 13), datetime(2023, 4, 12))`

![future-dates](https://user-images.githubusercontent.com/733563/231898204-5a7f9409-91d0-4676-bceb-6f5a1d871a29.png)

This this export of the jupyter notebook:
https://github.com/microsoft/farmvibes-ai/files/11227038/timelapse_visualization-Thomas40.pdf

**Comment by rafaspadilha** [comment]
Hi, @richstep. [Great Scott! Seems like your FarmVibes instance is hitting 88 mph](https://media.giphy.com/media/ZhESFK96NxbuO1yDgy/giphy.gif). 

Jokes aside, thanks for raising this.

SpaceEye works with a window of 48 days by default (the parameter `duration` of the SpaceEye workflow, whose documentation can be seen by running `client.document_workflow("data_ingestion/spaceeye/spaceeye_interpolation")`). 

If your time range is smaller than that, we add a padding to fill the whole temporal window. In your scenario, your time range has 33 days (March 13th to April 14th), so the difference (15 days) is added as padding. SpaceEye will generate a cloud-free image for each day of the window (with a damped interpolation approach, in the particular case of the [workflow used in the timelapse notebook](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/sentinel/spaceeye_ndvi.yaml)). 

That is why you are seeing rasters outside your input time range. If you check the number of SpaceEye or NDVI outputs, there will be 48 of them. You will also see a number of rasters that are before your time range, which were not downloaded, but were instead generated by SpaceEye.


A few possibilities to consider:

1. Ignore the rasters outside your input time range.  

2. Increase the time range to consider days before March 13th. Adding more days to fill the whole window will potentially improve the overall quality of the output rasters, as more data will be available for SpaceEye.

3. Decrease the `duration` value when running the workflow. This, in turn, means SpaceEye will have less available input data to generate the pixels originally occluded by clouds, which may decrease the quality of the results. This can be done directly altering the [yaml file of the custom workflow](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/sentinel/spaceeye_ndvi.yaml), for example, if you want to change `duration` to 30 days:

```
name: spaceeye_ndvi
sources:
  user_input:
    - spaceeye.user_input
sinks:
  ndvi: ndvi.index_raster
  spaceeye_raster: spaceeye.raster
parameters:
  pc_key:
tasks:
  spaceeye:
    workflow: data_ingestion/spaceeye/spaceeye_interpolation
    parameters:
      pc_key: "@from(pc_key)"
      duration: 30
  ndvi:
    workflow: data_processing/index/index
    parameters:
      index: ndvi
edges:
  - origin: spaceeye.raster
    destination:
      - ndvi.raster
```
